from __future__ import annotations

from typing import Any, Dict, Optional

E_AMEND_VALIDATION_SCHEMA = "E_AMEND_VALIDATION_SCHEMA"
E_AMEND_CAPABILITY_UNSUPPORTED = "E_AMEND_CAPABILITY_UNSUPPORTED"
E_AMEND_CAPABILITY_LIMIT = "E_AMEND_CAPABILITY_LIMIT"
E_AMEND_TARGET_NOT_FOUND = "E_AMEND_TARGET_NOT_FOUND"
E_AMEND_TARGET_AMBIGUOUS = "E_AMEND_TARGET_AMBIGUOUS"
E_AMEND_TARGET_MISMATCH = "E_AMEND_TARGET_MISMATCH"
E_AMEND_POLICY_DESTRUCTIVE_REFUSED = "E_AMEND_POLICY_DESTRUCTIVE_REFUSED"
E_AMEND_POLICY_OUTPUT_REWIRE_REFUSED = "E_AMEND_POLICY_OUTPUT_REWIRE_REFUSED"
E_AMEND_POLICY_APPROX_REFUSED = "E_AMEND_POLICY_APPROX_REFUSED"
E_AMEND_OUTPUT_TABLE_COLLISION = "E_AMEND_OUTPUT_TABLE_COLLISION"
E_AMEND_ASSERTION_ID_COLLISION = "E_AMEND_ASSERTION_ID_COLLISION"
E_AMEND_ASSERTION_ID_REQUIRED = "E_AMEND_ASSERTION_ID_REQUIRED"
E_AMEND_PATH_NOT_FOUND = "E_AMEND_PATH_NOT_FOUND"
E_AMEND_PATH_INVALID = "E_AMEND_PATH_INVALID"
E_AMEND_EXPR_INVALID = "E_AMEND_EXPR_INVALID"
E_AMEND_INDEX_OUT_OF_RANGE = "E_AMEND_INDEX_OUT_OF_RANGE"
E_AMEND_IR_INVALID = "E_AMEND_IR_INVALID"
E_AMEND_IR_INVARIANT_BREACH = "E_AMEND_IR_INVARIANT_BREACH"
E_AMEND_NO_OP = "E_AMEND_NO_OP"


def refusal(
    code: str,
    message: str,
    *,
    loc: Optional[Any] = None,
    hint: Optional[str] = None,
    meta: Optional[Dict[str, Any]] = None,
) -> Dict[str, Any]:
    return {
        "code": code,
        "message": message,
        "loc": loc,
        "hint": hint,
        "meta": meta or {},
    }

